- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    NUMBER: 78
  tasks:
  - name: Given number is grater than 100
    ansible.builtin.debug:
      msg: " Given number is: {{ Number }} is grater than 100 "
    when: NUMBER < 100

  - name: Given number is less than or equal to 100
    ansible.builtin.debug:
      msg: " Given number is: {{ NUMBER }} is less than or qual to 100 "
