- name: ansible data types
  hosts: local
  connection: local
  vars:
    DURATION: 120 # This is number
    COURSE: "devops with aws" # This is string
    IS_LIVE: true # This is boolean
    TOOLS: # List []
    - Linux
    - shell
    - Ansible
    CONCEPTS: # This is map or directory or object refferred as {}
      CI: Jenkins
      SCRIPTING: "shell, ansible, terraform, python"
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, duration is {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{TOOLS}}, concepts are: {{CONCEPTS}}"