- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: "Hellow i am learning course {{ COURSE }}, course duration: {{ DURATION }}, Triner is: {{ TRINER }}"