- name: nginx install and run
  hosts: frontend
  become: yes #here sudo access given to install the nginx server
  taks:
- name: install nginx server
  ansible.builtin.package:
    name: nginx
    state: present
- name: start nginx
  ansible.builtin.service:
  name: nginx
  state: started
  enabled: yes